-- CineBook DB schema for PostgreSQL / Supabase
-- Use lowercase snake_case names to work cleanly with PostgreSQL and Laravel.

CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fullname varchar(255),
  avatar varchar(255),
  username varchar(255) UNIQUE,
  password varchar(255),
  email varchar(255) UNIQUE NOT NULL,
  phone varchar(255),
  security_code varchar(255),
  google_id varchar(255) UNIQUE,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cinemas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255),
  address text
);

CREATE TABLE IF NOT EXISTS subtitles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255)
);

CREATE TABLE IF NOT EXISTS movies (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255),
  genre varchar(255),
  duration integer,
  release_date date,
  director varchar(255),
  description text,
  poster varchar(255),
  actors text,
  age_limit integer,
  trailer_link varchar(255)
);

CREATE TABLE IF NOT EXISTS rooms (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255),
  cinema_id integer,
  seat_count integer,
  CONSTRAINT fk_rooms_cinema FOREIGN KEY (cinema_id) REFERENCES cinemas (id)
);

CREATE TABLE IF NOT EXISTS seats (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id integer,
  seat_name varchar(255),
  seat_type varchar(255),
  CONSTRAINT fk_seats_room FOREIGN KEY (room_id) REFERENCES rooms (id)
);

CREATE TABLE IF NOT EXISTS showtimes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movie_id integer,
  room_id integer,
  subtitle_id integer,
  start_time timestamp,
  CONSTRAINT fk_showtimes_movie FOREIGN KEY (movie_id) REFERENCES movies (id),
  CONSTRAINT fk_showtimes_room FOREIGN KEY (room_id) REFERENCES rooms (id),
  CONSTRAINT fk_showtimes_subtitle FOREIGN KEY (subtitle_id) REFERENCES subtitles (id)
);

CREATE TABLE IF NOT EXISTS ratings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer,
  movie_id integer,
  rate integer,
  comment text,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ratings_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_ratings_movie FOREIGN KEY (movie_id) REFERENCES movies (id)
);

CREATE TABLE IF NOT EXISTS feedbacks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer,
  title varchar(255),
  context text,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_feedbacks_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS tickets (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer,
  showtime_id integer,
  fullname varchar(255),
  email varchar(255),
  phone varchar(255),
  booking_date timestamp DEFAULT CURRENT_TIMESTAMP,
  total_price numeric(10,2),
  CONSTRAINT fk_tickets_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_tickets_showtime FOREIGN KEY (showtime_id) REFERENCES showtimes (id)
);

CREATE TABLE IF NOT EXISTS ticket_details (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id integer,
  seat_id integer,
  price_at_booking numeric(10,2),
  CONSTRAINT fk_ticketdetails_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id),
  CONSTRAINT fk_ticketdetails_seat FOREIGN KEY (seat_id) REFERENCES seats (id)
);

INSERT INTO movies (
  name,
  genre,
  duration,
  release_date,
  director,
  description,
  poster,
  actors,
  age_limit,
  trailer_link
)
VALUES
  ('Sample Movie A', 'Action', 120, '2026-03-01', 'Director A', 'An action packed adventure.', '', 'Actor A, Actor B', 13, ''),
  ('Sample Movie B', 'Drama', 100, '2026-04-15', 'Director B', 'A heartfelt drama.', '', 'Actor C, Actor D', 16, '')
ON CONFLICT DO NOTHING;
